# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

# SimpleCoin Project Kelompok 5
# Code by Muhammad Alfaridzi
# login ui...
import sys
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(994, 665)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 1, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard = QtWidgets.QWidget()
        self.dashboard.setObjectName("dashboard")
        self.label = QtWidgets.QLabel(parent=self.dashboard)
        self.label.setGeometry(QtCore.QRect(210, 140, 251, 181))
        self.label.setObjectName("label")
        self.stackedWidget.addWidget(self.dashboard)
        self.send_rec = QtWidgets.QWidget()
        self.send_rec.setObjectName("send_rec")
        self.label_3 = QtWidgets.QLabel(parent=self.send_rec)
        self.label_3.setGeometry(QtCore.QRect(210, 160, 251, 181))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.send_rec)
        self.buy_sell = QtWidgets.QWidget()
        self.buy_sell.setObjectName("buy_sell")
        self.label_5 = QtWidgets.QLabel(parent=self.buy_sell)
        self.label_5.setGeometry(QtCore.QRect(220, 170, 251, 181))
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.buy_sell)
        self.public_records = QtWidgets.QWidget()
        self.public_records.setObjectName("public_records")
        self.label_4 = QtWidgets.QLabel(parent=self.public_records)
        self.label_4.setGeometry(QtCore.QRect(200, 160, 251, 181))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.public_records)
        self.transaction_history = QtWidgets.QWidget()
        self.transaction_history.setObjectName("transaction_history")
        self.label_6 = QtWidgets.QLabel(parent=self.transaction_history)
        self.label_6.setGeometry(QtCore.QRect(240, 130, 251, 181))
        self.label_6.setObjectName("label_6")
        self.stackedWidget.addWidget(self.transaction_history)
        self.about = QtWidgets.QWidget()
        self.about.setObjectName("about")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.about)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.about)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, -170, 451, 411))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/simplecoin-banner.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(240, 70, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans Semibold")
        font.setPointSize(14)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.frame)
        self.label_8 = QtWidgets.QLabel(parent=self.about)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.about)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(parent=self.about)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.stackedWidget.addWidget(self.about)
        self.gridLayout.addWidget(self.stackedWidget, 1, 2, 1, 1)
        self.listWidget_icon_only = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget_icon_only.setMaximumSize(QtCore.QSize(55, 16777215))
        self.listWidget_icon_only.setObjectName("listWidget_icon_only")
        self.gridLayout.addWidget(self.listWidget_icon_only, 1, 0, 1, 1)
        self.title_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_frame.setObjectName("title_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_icon = QtWidgets.QLabel(parent=self.title_frame)
        self.title_icon.setObjectName("title_icon")
        self.horizontalLayout.addWidget(self.title_icon)
        self.title_label = QtWidgets.QLabel(parent=self.title_frame)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.menu_btn = QtWidgets.QPushButton(parent=self.title_frame)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout.addWidget(self.menu_btn)
        self.gridLayout.addWidget(self.title_frame, 0, 0, 1, 2)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setStyleSheet("background-color: rgb(246, 255, 74);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 994, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "dashboard"))
        self.label_3.setText(_translate("MainWindow", "send rec"))
        self.label_5.setText(_translate("MainWindow", "buy sell"))
        self.label_4.setText(_translate("MainWindow", "public records"))
        self.label_6.setText(_translate("MainWindow", "transaction history"))
        self.label_7.setText(_translate("MainWindow", "SimpleCoin Project Kelompok 5"))
        self.label_8.setText(_translate("MainWindow", "1. Apa itu SimpleCoin?\n"
"SimpleCoin adalah sebuah alat transaksi Peer-to-Peer antar user dengan user & \n"
"tidak melibatkan pihak ketiga manapun seperti bank"))
        self.label_9.setText(_translate("MainWindow", "2. Latar belakang\n"
"Dengan perkembangan teknologi, pembayaran dan penyimpanan uang semakin canggih,\n"
"menjauhkan kita dari ketergantungan pada uang fisik (cashless).\n"
"Namun, transaksi keuangan elektronik masih bergantung pada pihak ketiga, seperti bank, yang\n"
"menghasilkan ketidakfisienan. Transaksi melalui bank memerlukan kepercayaan pada bank itu\n"
"sendiri, meningkatkan risiko keamanan dan privasi, sementara biaya transaksi yang tinggi,\n"
"terutama untuk layanan internasional, memberatkan pengguna.\n"
"Selain itu, akses terhadap layanan keuangan tidak merata di seluruh dunia, membatasi\n"
"pertumbuhan ekonomi di beberapa wilayah. Bank juga rentan terhadap gangguan eksternal, seperti\n"
"serangan siber, karena bergantung pada sistem keuangan sentral,\n"
"sementara transaksi bank sering memakan waktu berhari-hari, terutama untuk transfer antar negara atau\n"
"metode pembayaran khusus.\n"
""))
        self.label_10.setText(_translate("MainWindow", "3. SimpleCoin hadir sebagai solusi\n"
"SimpleCoin hadir menawarkan solusi pembayaran elektronik peer-to-peer yang artinya transaksi tidak dilakukan\n"
"lewat pihak ke tiga atau langsung dari user ke user. Solusi permasalahan lainnya seperti transaksi dapat \n"
"dilakukan untuk semua orang dimanapun & kapanpun, semua transaksi tercatat dan dapat dilihat oleh\n"
"publik, address yang transparant dan lain lain. \n"
""))
        self.title_icon.setText(_translate("MainWindow", "TextLabel"))
        self.title_label.setText(_translate("MainWindow", "TextLabel"))
        self.menu_btn.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
