# Form implementation generated from reading ui file 'transaction_detail_popup.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(396, 356)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/simplecoin_ico.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 401, 291))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.title = QtWidgets.QLabel(parent=self.frame)
        self.title.setGeometry(QtCore.QRect(10, 10, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 90, 381, 101))
        self.frame_3.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"border-color: rgb(217, 217, 217);\n"
"border-width: 10px;        \n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"margin: 1px;\n"
"padding:1px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.widget = QtWidgets.QWidget(parent=self.frame_3)
        self.widget.setGeometry(QtCore.QRect(0, -1, 381, 101))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.sender_or_receipent = QtWidgets.QLabel(parent=self.widget)
        self.sender_or_receipent.setGeometry(QtCore.QRect(0, 60, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.sender_or_receipent.setFont(font)
        self.sender_or_receipent.setObjectName("sender_or_receipent")
        self.date_information = QtWidgets.QLabel(parent=self.widget)
        self.date_information.setGeometry(QtCore.QRect(50, 0, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.date_information.setFont(font)
        self.date_information.setObjectName("date_information")
        self.status_information = QtWidgets.QLabel(parent=self.widget)
        self.status_information.setGeometry(QtCore.QRect(60, 30, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.status_information.setFont(font)
        self.status_information.setObjectName("status_information")
        self.Receipent_information = QtWidgets.QLabel(parent=self.widget)
        self.Receipent_information.setGeometry(QtCore.QRect(80, 60, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.Receipent_information.setFont(font)
        self.Receipent_information.setObjectName("Receipent_information")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame)
        self.frame_4.setGeometry(QtCore.QRect(10, 200, 381, 41))
        self.frame_4.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"background-color: rgb(217, 217, 217);\n"
"border-color: rgb(217, 217, 217);\n"
"border-width: 10px;        \n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"margin: 1px;\n"
"padding:1px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.network_fee = QtWidgets.QLabel(parent=self.frame_4)
        self.network_fee.setGeometry(QtCore.QRect(110, 0, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.network_fee.setFont(font)
        self.network_fee.setObjectName("network_fee")
        self.balance_information = QtWidgets.QLabel(parent=self.frame)
        self.balance_information.setGeometry(QtCore.QRect(10, 50, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.balance_information.setFont(font)
        self.balance_information.setObjectName("balance_information")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame)
        self.frame_5.setGeometry(QtCore.QRect(10, 250, 381, 41))
        self.frame_5.setStyleSheet("background-color: rgb(217, 217, 217);\n"
"background-color: rgb(217, 217, 217);\n"
"border-color: rgb(217, 217, 217);\n"
"border-width: 10px;        \n"
"border-style: solid;\n"
"border-radius: 10px;\n"
"margin: 1px;\n"
"padding:1px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.view_details_button = QtWidgets.QPushButton(parent=self.frame_5)
        self.view_details_button.setGeometry(QtCore.QRect(334, 0, 41, 41))
        self.view_details_button.setStyleSheet("")
        self.view_details_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/arrow-circle-right.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.view_details_button.setIcon(icon1)
        self.view_details_button.setIconSize(QtCore.QSize(25, 25))
        self.view_details_button.setObjectName("view_details_button")
        self.frame_5.raise_()
        self.title.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.balance_information.raise_()
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setGeometry(QtCore.QRect(0, 300, 401, 51))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.close_button = QtWidgets.QPushButton(parent=self.frame_2)
        self.close_button.setGeometry(QtCore.QRect(310, 10, 75, 31))
        self.close_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(217, 217, 217);\n"
"border-width: 1px;        \n"
"border-style: solid;\n"
"border-radius: 1px;\n"
"margin: 1px;\n"
"padding:1px;")
        self.close_button.setObjectName("close_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Transactions Detail"))
        self.title.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Transaction Detail</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "Date"))
        self.label_3.setText(_translate("Dialog", "Status"))
        self.sender_or_receipent.setText(_translate("Dialog", "Recipient"))
        self.date_information.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Date</p></body></html>"))
        self.status_information.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Status</p></body></html>"))
        self.Receipent_information.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">Receipent</p></body></html>"))
        self.label_5.setText(_translate("Dialog", "Network Fee"))
        self.network_fee.setText(_translate("Dialog", "<html><head/><body><p align=\"right\">network_fee</p></body></html>"))
        self.balance_information.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">-000001$SPC</p></body></html>"))
        self.label_6.setText(_translate("Dialog", "View Details"))
        self.close_button.setText(_translate("Dialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
